config/routes.rb
Rails.application.routes.draw do
  resources :techniques

  resources :fills

  resources :grooves

  resources :lesson_contents

  resources :users

  get '/signin', to: 'sessions#new'

  post '/signin', to: 'sessions#create'

end

app/models/fill.rb
class Fill < LessonContent
end

app/models/groove.rb
class Groove < LessonContent
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
  
end

app/models/lesson_content.rb
class LessonContent < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_and_belongs_to_many :note_values

  attr_accessor :note_values
  belongs_to :user
end

app/models/note_value.rb
class NoteValue < ActiveRecord::Base
  has_and_belongs_to_many :lesson_contents
end

app/models/technique.rb
class Technique < LessonContent
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def require_signin!
    if current_user.nil?
      flash[:error] = "You need to sign in or sign up to continue."
      redirect_to signin_url
    end
  end
  helper_method :require_signin!

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/fills_controller.rb
class FillsController < ApplicationController
  before_action :require_signin!, except: [:index, :show]

  def index
    @fills = Fill.all
  end

  def new
    @fill = Fill.new
  end

  def create
    @fill = Fill.new( fill_params)
    @fill.user = current_user

    if @fill.save
      flash[:notice] = "Fill was succesfully saved!"
      redirect_to fills_path
    else
      flash[:error] = "Something went wrong..."
      render :new
    end
  end

  private

  def fill_params
    params.require(:fill).permit(:image, :length, :audio, :video)
  end
end

app/controllers/grooves_controller.rb
class GroovesController < ApplicationController
  before_action :require_signin!, except: [:index, :show]

  def index
    @grooves = Groove.all
  end

  def show
    @groove = Groove.find(params[:id])
  end

  def new
    @groove = Groove.new
  end

  def create
    @groove = Groove.new( groove_params )
    @groove.user = current_user

    if @groove.save
      flash[:notice] = "Groove has been saved!"
      redirect_to grooves_path
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  private

  def groove_params
    params.require(:groove).permit(:image, :length, :audio, :video)
  end

  def associate_note_values 
  end
end

app/controllers/lesson_contents_controller.rb
class LessonContentsController < ApplicationController

  def index
    @lesson_contents = LessonContent.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(email: params[:signin][:email]).first

      if  user && user.authenticate(params[:signin][:password])

      session[:user_id] = user.id
      flash[:notice] = 'Signed in succesfully.'

      redirect_to root_url
    else
      flash[:error] = 'Sorry, something went wrong'
      render :new
    end
  end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new( user_params )

    if @user.save
      flash[:notice] = "You have signed up succesfully."
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private 
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fills_helper.rb
module FillsHelper
end

app/helpers/grooves_helper.rb
module GroovesHelper
end

app/helpers/lesson_contents_helper.rb
module LessonContentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fills/index.html.erb
<h2>Fills</h2>
<h3><%= link_to 'Add Fill', new_fill_path %></h3>
  <ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-5">
    <% @fills.each do |fill| %>
    <li><%= image_tag fill.image(:medium) %> </li>
    <% end %>
  </ul>

app/views/fills/new.html.erb
<h2>Add a new fill below</h2>
<%= simple_form_for @fill, :html => {:multipart => true } do |fill| %>
  <%= fill.label 'Select image file' %>
  <%= fill.file_field :image %>
  <%= fill.association :note_values, as: :check_boxes, label_method: :value, boolean_style: :inline %>
  <%= fill.input :length, label: 'Length in bars or beats' %>
  <%= fill.input :audio, label: 'Add a link to a soundcloud file' %>
  <%= fill.input :video, label: 'Add a youtube link below' %>
  <%= fill.button :submit %>
<% end %>

app/views/grooves/index.html.erb
<h1>Grooves</h1>
<%= link_to 'Add Groove', new_groove_path %>
  <ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-5">
<% @grooves.each do |g| %>
    <li><%= image_tag g.image(:original) %></li>
<% end %>
   </ul>

app/views/grooves/new.html.erb
<h2>Add a new groove below</h2>
<%= simple_form_for @groove, :html => {:multipart => true } do |groove| %>
  <%= groove.label 'Select image file' %>
  <%= groove.file_field :image %>
  <%# <%= groove.association :note_values, as: :check_boxes, label_method: :value, boolean_style: :inline %>
  <%= groove.input :length, label: 'Length in bars or beats' %>
  <%= groove.input :audio, label: 'Add a link to a soundcloud file' %>
  <%= groove.input :video, label: 'Add a youtube link below' %>
  <%= groove.button :submit %>
<% end %>

app/views/grooves/show.html.erb
<%= image_tag @groove.image.url(:original) %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to "Home", root_path %>
<%= link_to "Grooves", grooves_path %>
<%= link_to "Fills", fills_path %>
<%= link_to "Lesson Contents", lesson_contents_path %>
<% if current_user.nil? %>
  <%= link_to "Sign In", signin_path %>
  <%= link_to "Sign Up", new_user_path %>
<% else %>
  <%= current_user.email %>
  <%= link_to "Log Out" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Onlinedrumbook Com" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Onlinedrumbook Com" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/lesson_contents/index.html.erb
<table>
  <thead>
    <tr>
      <th width="200">Image</th>
      <th width="150">Content Type</th>
      <th width="150">Added By</th>
    </tr>
  </thead>
  <tbody>
<% @lesson_contents.each do |content| %>
    <tr>
      <td><%= image_tag content.image(:thumb) %></td>
      <td><%= content.type %></td>
      <td><%= content.user.username if content.user %></td>
    </tr>
    
  <% end %>
  </tbody>
</table>

app/views/pages/home.html.erb
<h1>This is the homepage</h1>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= simple_form_for @user do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit, value: "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>